config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', 		to: 'static_pages#help'
  get '/about', 	to: 'static_pages#about'
  get '/contact', 	to: 'static_pages#contact'
  get '/signup',	to: 'users#new'
  post '/signup',	to: 'users#create'
  get '/school',	to: 'users#school'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
									format: { with: VALID_EMAIL_REGEX },
									uniqueness: { case_sensitive: false }
	# has_secure_password
	#validates :password, presence: true, length: { minimum: 6 }
	validates :student_family_name, presence: true, length: { maximum: 20 }
	validates :student_first_given_name, presence: true, length: { maximum: 20 }
	validates :student_second_given_name, length: { maximum: 20 }
	validates :student_gender, presence: true, length: { maximum: 20 }
	validates :student_date_of_birth, presence: true, length: { maximum: 20 }
	validates :student_year_entering, presence: true, length: { maximum: 20 }
	validates :student_phone_number, length: { maximum: 20 }
	validates :caregiver_contact_number, presence: true, length: { maximum: 20 }
	validates :student_aboriginality, presence: true, length: { maximum: 20 }
	validates :student_lote, length: { maximum: 20 }
	validates :student_lote_first_language, presence: true, if: :lote?, length: { maximum: 20 }
	validates :student_lote_second_language, length: { maximum: 20 }

	def lote?
		student_lote == true
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def school
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Thank you for enrolling!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation, :student_family_name,
  								:student_first_given_name, :student_second_given_name, :student_gender,
  								:student_date_of_birth, :student_phone_number, :caregiver_contact_number,
  								:student_aboriginality, :student_lote, :student_lote_first_language,
  								:student_lote_second_language, :student_year_entering)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis
    def full_title(page_title = '')
        base_title = "Ruby on Rails Tutorial Sample App"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Merewether High School Enrollment Site v
	</small>

	<small>
		<%= SampleApp::Application::VERSION %>
	</small>

	<nav>
		<ul>
			<li><%= link_to "School View", school_path %></li>
			<!-- <li><%= link_to "About",	about_path  %></li>
			<li><%= link_to "Contact",	contact_path  %></li>
			<li><a href="#">News</a> -->
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MHS Enrollment", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <!-- <li><%= link_to "Help",   help_path %></li> -->
        <!-- <li><%= link_to "Log in", '#' %></li> -->
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_railhead.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all',
                                             'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/railhead' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
    The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
    Tutorial</em></a> is a
    <a href="https://www.railstutorial.org/book">book</a> and
    <a href="http://screencasts.railstutorial.org/">screencast series</a>
    to teach web development with
    <a href="http://rubyonrails.org/">Ruby on Rails</a>.
    This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
    Contact the Ruby on Rails Tutorial about the sample app at the
    <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
    Get help on the Ruby on Rails Tutorial at the
    <a href="https://www.railstutorial.org/help">Rails Tutorial help page</a>.
    To get help on this sample app, see the
    <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>MHS Enrollment Site</h1>

	<h2>
		Click the link below to submit an enrollment.
	</h2>

	<%= link_to "Enrol", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= image_tag("mhs.PNG", alt: "MHS Logo", size: "100x100") %>

app/views/users/new.html.erb
<% provide(:title, 'Enrol') %>
<h1>Enrol</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= %>
        <h2>Caregiver</h2>
      <% %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <!-- <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %> -->

      <%= f.label :caregiver_contact_number, "Caregiver contact number" %>
      <%= f.text_field :caregiver_contact_number, maxlength: 10, class: 'form-control' %>

      <%= %>
        <h2>Student</h2>
      <% %>

      <%= f.label :student_family_name, "Family name" %>
      <%= f.text_field :student_family_name, class: 'form-control' %>

      <%= f.label :student_first_given_name, "First given name" %>
      <%= f.text_field :student_first_given_name, class: 'form-control' %>

      <%= f.label :student_second_given_name, "Second given name" %>
      <%= f.text_field :student_second_given_name, class: 'form-control' %>

      <%= f.label :student_gender, "Gender" %>
      <%= f.select :student_gender, [["Male"], ["Female"]], class: 'form-control' %>

      <%= f.label :student_date_of_birth, "Date of birth" %>
      <%= f.date_field :student_date_of_birth, max: Date.today, min: 18.years.ago, class: 'form-control' %>

      <%= f.label :student_phone_number, "Phone number" %>
      <%= f.text_field :student_phone_number, maxlength: 10, class: 'form-control' %>

      <%= f.label :student_aboriginality, "Aboriginality" %>
      <%= f.select :student_aboriginality, [["None"], ["Aboriginal"], ["Torres Strait Islander"], ["Both"]] , class: 'form-control' %>

      <%= f.label :student_lote, "Any other languages other than english spoken at home?" %>
      <%= f.select :student_lote, [["False", false], ["True", true]] , class: 'form-control' %>

      <%= f.label :student_lote_first_language, "First language" %>
      <%= f.text_field :student_lote_first_language, class: 'form-control' %>

      <%= f.label :student_lote_second_language, "Other language" %>
      <%= f.text_field :student_lote_second_language, class: 'form-control' %>

      <%= f.label :student_year_entering, "Year entering" %>
      <%= f.select :student_year_entering, [7,8,9,10,11,12] , class: 'form-control' %>

      <%= f.submit "Enrol now", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/school.html.erb
<%= provide(:title, "Enrollments") %>

<h1>Enrollment List</h1>

<% @users.each do |user| %>
    <li class="test">
        <%= link_to "#{user.student_first_given_name} #{user.student_family_name} - Year #{user.student_year_entering}", user %>
    </li>
<% end %>

app/views/users/show.html.erb
<%= provide(:title, @user.student_first_given_name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= @user.student_first_given_name %>
			</h1>

			<% for attribute in @user.attributes.keys %>
			  <p><em><strong><%= attribute.humanize.upcase %></strong></em>: <%= @user.attributes[attribute].to_s %></p>
			<% end %>

		</section>
	</aside>
</div>